### ISSUE TITLE
Setting _FillValue dataset attribute should affect its fill value creation property

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#27]
The value of the ``_FillValue`` dataset attribute is not propagated to that dataset's fill value creation property. (@gheber: Where does this makes sense to implement? Rules or app code?)

**Comment by gheber** [comment]
If that's the conventions intention, it should happen during HDF materialization, i.e., there should be a rule which says, "If the variable to be created has a '_FillValue' attribute => make sure it gets materialized as a dataset creation property."

**Comment by ajelenak-thg** [comment]
> If that's the conventions intention

Yes, it is. Data readers, at least better ones, can look up that value in order to more intelligently interpret dataset's data. Since fill value is a dataset creation property _FillValue's value should be determined before a new dataset is created. Not sure but this potentially mixes conventions and creation of new datasets. Where could _FillValue's value be entered? new dataset dialog window?

**Comment by gheber** [comment]
Not sure. Maybe Joe has an idea. One of the problems is type. Obviously, the fill value must be of the type of the underlying dataset (or convertible...). All the rules, e.g., NUG, will tell you is that a variable must have a _FillValue attribute of the variable's type. We could add a default to the convention's configuration file, but the user should, of course, have the ability to change it.

**Comment by hyoklee** [comment]
@ajelenak-thg What do you mean by "dataset's fill value creation property"? Is there a special arrangement in HDF5 Json for such thing?

**Comment by ajelenak-thg** [comment]
Yes: http://hdf5-json.readthedocs.org/en/latest/bnf/dataset.html#grammar-token-dcpl

Something like:

```json
{
    "shape": {"..."},
    "type": {"..."},
    "creationProperties": {
        "fillValue": -9999
    }
}
```

**Comment by hyoklee** [comment]
I think server can fill in by copying dataset's _FillValue attribute value if it is set and CF convention is used on design.  If type doesn't match throw an error if and only if CF convention is set on the design.

**Comment by ajelenak-thg** [comment]
This issue was mentioned in the last user meeting so I added it to the Milestone 1.1.

**Comment by hyoklee** [comment]
User is more interested in filling in dataset with _FillValue value. Updating creationProperty will not help user that much.  I hope that milestone 1.1 can address bigger picture issue such as data generation, not tiny one like GUI improvements and fixing minor things like this.

**Comment by ajelenak-thg** [comment]
> User is more interested in filling in dataset with _FillValue value.

Isn't that what setting fill value in the dataset creation property list does? Why do it "manually" when the library can do it automatically for us?

**Comment by hyoklee** [comment]
What's the point of setting *all* values with 0 or _FillValue of a particular dataset? What user needs is the ability to set a certain region of dataset as FillValue and the rest with random/sequential/Gaussian values. HPD should support a world map and let user select a particular region (such as Florida) and apply either sea or land as FillValue. That's more important in my opinion and will help data producers.

**Comment by hyoklee** [comment]
I'll start working on this issue.

**Comment by hyoklee** [comment]
Here's the design:

If CF convention is active, HPD Desktop will sync _FillValue with creationProperty. If not, CRUD operation of _FillValue will not affect creation Property. 

Edit box for fillvalue will appear in a new dataset / edit dataset dialog box for non-CF case. 

HPD Server should do additional checking whether it's synced or not when CF convention is active.

**Comment by ajelenak-thg** [comment]
[NUG](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf/Attribute-Conventions.html#Attribute-Conventions) uses `_FillValue` in the same way.
