### ISSUE TITLE
Windows 8 install error

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#40]
From our beta tester (Arif):

> I tried to install the product designer to windows 8 machine. I got following error. The application has failed to start because its side by side configuration is incorrect.

**Comment by hyoklee** [comment]
I'm aware of the issue but SAG is not fast enough to get Win8 build machine: https://jira.hdfgroup.uiuc.edu/browse/SYSADMIN-3490

**Comment by hyoklee** [comment]
In the mean time, can you ask Arif to try:

http://hdfeos.org/software/hpd/1.0.0/HPD8.exe

If it runs successfully on his Win8?

**Comment by hyoklee** [comment]
Win8 is now supported because SAG has provided a VM for me.
