### ISSUE TITLE
Code crashes when project is closed if inline editing is on

### ISSUE THREAD

**Issue by tedhabermann** [HDFGroup/hpd#53]
When I open a project and click on the name of the project I go into inline editing mode. If I close the project while in that mode, HPD crashes. If project names are not editable, they should not switch to inline editing mode.

**Comment by hyoklee** [comment]
I'll be working on this issue now.

**Comment by hyoklee** [comment]
It doesn't happen on Windows - only Mac and linux. I think wxPython is not a good choice for cross-platform application.

**Comment by hyoklee** [comment]
Patch is made in #75.
