### ISSUE TITLE
The New Design dialog

### ISSUE THREAD

**Issue by tedhabermann** [HDFGroup/hpd#54]
This dialog has several problems. The name user interface element must be 2-3 times wider and the description user interface should be wider and support multiple lines like a description. If it can be resizable, that would be great.

**Comment by hyoklee** [comment]
I fixed it but Linux doesn't support multi-liner so Linux app will look different (one liner for description) from Mac/Windows version.

**Comment by hyoklee** [comment]
Pull request #90 will fix this issue on Mac or Windows.
