### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by tedhabermann** [HDFGroup/hpd#56]
The windows I open in most Mac applications have white backgrounds. The Product Designer should have a white background on Macs.

**Comment by hyoklee** [comment]
This is quite tough to change because HPD icons use white/black. If I change it to white background, you won't see highlighted font in white and white icons.

**Comment by tedhabermann** [comment]
What icons does HDFView use?

**Comment by hyoklee** [comment]
I picked modern icons with mobile platform in mind.  HDFView icons are not portable and I don't want to use them. 

https://github.com/google/material-design-icons

**Comment by ajelenak-thg** [comment]
How about reducing the grayness of the background? On my Mac laptop I can barely see the drop-down triangle when, for example, dataset has attributes or for viewing compound datatype members.

Is it possible to modify the color of these black-and-white icons?

**Comment by hyoklee** [comment]
Pull request #93 fixes this issue.
