### ISSUE TITLE
NcML file name restrictions

### ISSUE THREAD

**Issue by tedhabermann** [HDFGroup/hpd#57]
The NcML import only allows files that end with .ncml. I think this is overly restrictive and causes problems with other tools. For example, it appears that Oxygen will not save an xml file with a .ncml extension (testing that). Is there an anyText file restriction that we can use instead of an extension restriction?

**Comment by ajelenak-thg** [comment]
@tedhabermann Would using `.ncml` and `.xml` be enough? How likely is to have a `.txt` file with NcML in it?

**Comment by tedhabermann** [comment]
@ajelenak-thg - I'm not sure why Product Designer should make assumptions about extensions. Maybe required in windows...??? I think .xml or .ncml would be better than just .ncml...

**Comment by hyoklee** [comment]
See merge request #79.
