### ISSUE TITLE
ncml import

### ISSUE THREAD

**Issue by tedhabermann** [HDFGroup/hpd#59]
I am trying to import an ncml file but only a small part of it imports. The import ends at string type = cit:CI_Organisation. I need the entire file to import... The contents are:

```xml
<nc:netcdf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2"
           xmlns:nc="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2"
           xmlns:xlink="http://www.w3.org/1999/xlink">
   <nc:group name="cit:CI_Responsibility">
      <nc:attribute name="type" value="cit:CI_Responsibility"/>
      <nc:attribute name="id" value="indOrg"/>
      <nc:group name="cit:role">
         <nc:attribute name="type" value="cit:CI_RoleCode"/>
         <nc:attribute name="codeList" value="codeListLocation#CI_RoleCode"/>
         <nc:attribute name="codeListValue" value="pointOfContact"/>
      </nc:group>
      <nc:group name="cit:party">
         <nc:attribute name="type" value="cit:CI_Organisation"/>
         <nc:attribute name="cit:name" value="organizationName" type="gco:CharacterString"/>
         <nc:group name="cit:contactInfo">
            <nc:attribute name="type" value="cit:CI_Contact"/>
            <nc:group name="cit:phone">
               <nc:attribute name="type" value="cit:CI_Telephone"/>
               <nc:attribute name="cit:number" value="voiceNumber" type="gco:CharacterString"/>
               <nc:group name="cit:numberType">
                  <nc:attribute name="type" value="cit:CI_TelephoneTypeCode"/>
                  <nc:attribute name="codeList" value="codeListLocation#CI_TelephoneTypeCode"/>
                  <nc:attribute name="codeListValue" value="voice"/>
               </nc:group>
            </nc:group>
            <nc:group name="cit:phone_d1e21">
               <nc:attribute name="role" value="cit:phone"/>
               <nc:attribute name="type" value="cit:CI_Telephone"/>
               <nc:attribute name="cit:number" value="faxNumber" type="gco:CharacterString"/>
               <nc:group name="cit:numberType">
                  <nc:attribute name="type" value="cit:CI_TelephoneTypeCode"/>
                  <nc:attribute name="codeList" value="codeListLocation#CI_TelephoneTypeCode"/>
                  <nc:attribute name="codeListValue" value="facsimile"/>
               </nc:group>
            </nc:group>
            <nc:group name="cit:address">
               <nc:attribute name="type" value="cit:CI_Address"/>
               <nc:attribute name="cit:deliveryPoint"
                             value="deliveryPoint"
                             type="gco:CharacterString"/>
               <nc:attribute name="cit:city" value="city" type="gco:CharacterString"/>
               <nc:attribute name="cit:administrativeArea"
                             value="administrativeArea"
                             type="gco:CharacterString"/>
               <nc:group name="cit:CI_Address">
                  <nc:attribute name="type" value="cit:postalCode"/>
                  <nc:attribute name="cit:postalCode" value="postalCode" type="gco:CharacterString"/>
               </nc:group>
               <nc:attribute name="cit:country" value="country" type="gco:CharacterString"/>
               <nc:attribute name="cit:electronicMailAddress"
                             value="electronicMailAddress "
                             type="gco:CharacterString"/>
            </nc:group>
            <nc:attribute name="cit:hoursOfService"
                          value="hoursOfService"
                          type="gco:CharacterString"/>
         </nc:group>
         <nc:group name="cit:individual">
            <nc:attribute name="type" value="cit:CI_Individual"/>
            <nc:attribute name="cit:name" value="individualName" type="gco:CharacterString"/>
         </nc:group>
      </nc:group>
   </nc:group>
</nc:netcdf>
```

**Comment by hyoklee** [comment]
I don't know what generated this mcml output but it's not valid. type should be one of

```
byte, short, int, long, float, double, char, string (modified)
```

If I replace gco:CharacterString to string, I can import it. See Sandbox/issue59 design from product designer that I imported.

**Comment by ajelenak-thg** [comment]
Related question: What happens if an import operation fails? Is the partially imported design removed?

**Comment by tedhabermann** [comment]
Currently the design is not removed and there is no error message...

**Comment by tedhabermann** [comment]
@hyoklee - this raises an interesting question - is it Product Designer's job to validate ncml during the design process? I have a problem that I am trying to use the type attribute to define UML classes for groups. Unfortunately, the ncml schema only allows primitive types. This works well for variables and (maybe) attributes, but it makes no sense in the case of groups (you can not have a group that is an integer. I can change the schema to add a different attribute for groups (maybe class???). Maybe that makes sense, but, the XML would still be invalid w/r to the existing schema... which brings us back to the original question... Should Product Designer be validating XMLat this point???

**Comment by hyoklee** [comment]
NcML importer will stop where the error occurs without deleting design and it's documented already:

http://hpd.readthedocs.org/en/new-docs/usage.html#import-ncml

All importers do their best to import contents as much as they can. Thus, I don't think deleting design is not a good idea when error occurs. 

.xml is reserved for h4map. I'd like to distinguish NcML from H4MAP.

**Comment by tedhabermann** [comment]
XML is a method for representing data and information that is used in many "formats". Reserving the xml extension for only one (fairly obscure) XML language (H4MAP) seems overly restrictive and will almost certainly cause more problems for users than is solves. I suggest we minimize import extension restrictions as much as possible. This is a tool for the design phase and we need to keep it general and flexible to enable users to experiment and explore ideas. Welding in extension restrictions is not consistent with that requirement.

A similar case can be made for validating input past well-formedness. XML files must be well formed so that the structure makes sense, but we should not prevent users from importing XML files that are not schema-valid. Again, that decision could limit the ideas that designers can explore. In my opinion, we should notify users if invalidity causes problems in outputting HDF5, but not before...

**Comment by hyoklee** [comment]
OK. I'll add *.* extension for all importers.

**Comment by tedhabermann** [comment]
Deleting a design with an import error - seems to me that typical workflow would be to correct error in the file being imported and then reimport, hoping to get the whole design. Can we reimport over the same name? I would expect that to be the most common use case when import errors occur (at least it is what i would like to do). Do I need to delete the broken design first, then re-import?

**Comment by hyoklee** [comment]
When you reimport, HPD will ask 'delete existing one' if same name of design is found.

**Comment by tedhabermann** [comment]
Great! Then user can decide whether to keep the semi-design...

**Comment by ajelenak-thg** [comment]
If I start the app normally there is no console window to show import errors. I think the import error should be displayed in a message box.

**Comment by hyoklee** [comment]
Go to "Apps > Utilities > Console" to view not-so-important warning/info messages that you will never want to see in annoying pop-ups.

**Comment by ajelenak-thg** [comment]
> to view not-so-important warning/info messages that you will never want to see in annoying pop-ups.

Exactly! Why make it so complicated to see a simple import error? Why mix a GUI app with all the other system messages.

**Comment by hyoklee** [comment]
It's complicated only on Mac. Linux/Windows has no problem in seeing them at the terminal.

**Comment by tedhabermann** [comment]
I agree 100% with Aleksandar on this one. No user looks at the console for error messages in any application with a graphical user interface. The only time we see something like that is when an app crashes and we send a message to Apple. All product designer messages (positive and negative) need to be presented in a consistent way through the GUI. I think this question was addressed awhile ago by some code that Aleks wrote for catching and reporting errors. We need to use that code (or similar code that does the same thing) throughout the application.

**Comment by hyoklee** [comment]
I've already issued #61.
