### ISSUE TITLE
DIMENSION_LIST attribute values in dimscale design not in correct format

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#7]
According to h5serv's [dim_scale.json](https://github.com/HDFGroup/h5serv/blob/5a5fc13c5a9fe04a42e1dfc3996b1fe3cd76bb31/testjson/dim_scale.json#L296) the value of DIMENSION_LIST attribute should be a list of lists. The dimscale design in PD server has this value just as a list.

**Comment by hyoklee** [comment]
@jready Why should it be list of lists?

**Comment by ajelenak-thg** [comment]
Perhaps because there can be more than one dimension scale attached to the same dataset's dimension?

**Comment by Jready** [comment]
@hyoklee I believe you have tagged me by mistake. I could look into this if you like but I am unasociated with this git.

**Comment by hyoklee** [comment]
@jready Sorry. It's my mistake.

**Comment by hyoklee** [comment]
I think I fixed it on server. Can you validate it?

**Comment by jreadey** [comment]
FYI: This is the program that I used to create dim_scale.h5 (which I later converted to dim_scale.json):

import h5py
import numpy as np

f = h5py.File("mydimscale.h5", "w")
dset = f.create_dataset('temperatures', (10, 10, 10), dtype='f')
dset.attrs['temp_units'] = "C"
f.create_dataset('scale_x', data=np.arange(10)*10e3)
f.create_dataset('scale_y', data=np.arange(10)*10e3)
f.create_dataset('scale_z', data=np.arange(10)*10e3)
dset.dims.create_scale(f['scale_x'], "Simulation X (North) axis")
dset.dims.create_scale(f['scale_y'], "Simulation Y (East) axis")
dset.dims.create_scale(f['scale_z'], "Simulation Z (Vertical) axis")
dset.dims[0].attach_scale(f['scale_x'])
dset.dims[1].attach_scale(f['scale_y'])
dset.dims[2].attach_scale(f['scale_z'])
f.close()

**Comment by ajelenak-thg** [comment]
> I think I fixed it on server. Can you validate it?

Fixed.
