### ISSUE TITLE
1D string array attribute's dataspace is converted to scalar on HDF5/JSON import

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#76]
When importing this HDF5/JSON:
```json
{
    "apiVersion": "1.0.0",
    "datasets": {
        "a9217e6b-7bf7-11e4-9645-3c15c2da029e": {
            "attributes": [
                {
                    "name": "A1",
                    "shape": {
                        "class": "H5S_SIMPLE",
                        "dims": [5]
                    },
                    "type": {
                        "class": "H5T_STRING",
                        "charSet": "H5T_CSET_ASCII",
                        "strPad": "H5T_STR_NULLTERM",
                        "length": 7
                    },
                    "value": [
                        "Parting",
                        "is such",
                        "sweet",
                        "sorrow.",
                        "1234567890"
                    ]
                }
            ],
            "shape": {
                "class": "H5S_SIMPLE",
                "dims": [15]
            },
            "type": {
                "base": "H5T_STD_I32LE",
                "class": "H5T_INTEGER"
            }
        }
    },
    "groups": {
        "a9208b38-7bf7-11e4-b1be-3c15c2da029e": {
            "links": [
                {
                    "id": "a9217e6b-7bf7-11e4-9645-3c15c2da029e",
                    "class": "H5L_TYPE_HARD",
                    "collection": "datasets",
                    "title": "DS1"
                }
            ]
        }
    },
    "root": "a9208b38-7bf7-11e4-b1be-3c15c2da029e"
}
```
The `A1` attribute's dataspace is converted from:
```
                    "shape": {
                        "class": "H5S_SIMPLE",
                        "dims": [5]
                    },
```
to:
```
                    "shape": {
                        "class": "H5S_SCALAR"
                    },
```

**Comment by hyoklee** [comment]
As far as I know, nectCDF doesn't allow array of string attributes. HPD should not produce such JSON. Did you create the above JSON by yourself with an editor?

**Comment by hyoklee** [comment]
Also, does server throw an error on such input?

**Comment by ajelenak-thg** [comment]
I think we have many HDF4 Map imports in Sandbox with string array attributes. You submitted a bug/blocker issue few weeks ago because the MATLAB code generator could not handle such attributes. 

Should all those HDF4 imports be flagged as invalid now? netCDF-4 allows creating string array attributes. We support compound and arrays datatypes, very seldom used in the netCDF world. At the very least users should be alerted to this conversion, not perform it silently. Or raise an error and stop because typically such attributes will come with values so just silently altering their shape is not enough.

My vote is to support string array attributes.

**Comment by hyoklee** [comment]
I think it's a bug in hdf4 importer particularly with ODL parser in string handling. I located the code so I'll fix it later. 

Array of string attributes never should be supported for netCDF/CF interoperability in my opinion. If array of string is desired, user should use dataset, not attribute. 

Please do whatever you can at the server level to stop accepting such non-interoperable attribute input. I'll also add such check following  your input validator.

**Comment by ajelenak-thg** [comment]
netCDF/CF interoperability is a fuzzy issue. We do support groups and they are strictly speaking not netCDF/CF compatible. What you propose is much more work then simply modifying the HDF5/JSON importer code to support string array attributes. Looks like nothing else needs to change.

**Comment by hyoklee** [comment]
I want to be practical here. netCDF-Java/NcML will not work with array of strings attribute. Group/compound are supported pretty well in both netCDF-Java and netCDF-C.

**Comment by ajelenak-thg** [comment]
```
$ ncdump -h test.nc
netcdf test {

// global attributes:
		string :attr = "Let but your honour know", "Whom I believe to be most strait in virtue", "That, in the working of your own affections", "Had time cohered with place or place with wishing", "Or that the resolute acting of your blood", "Could have attain’d the effect of your own purpose", "Whether you had not sometime in your life", "Err’d in this point which now you censure him", "And pull’d the law upon you." ;
}
```
And this is from ToolsUI:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ncml:netcdf xmlns:ncml="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2">
  <ncml:attribute name="attr" value="Let but your honour know,Whom I believe to be most strait in virtue,That, in the working of your own affections,Had time cohered with place or place with wishing,Or that the resolute acting of your blood,Could have attain’d the effect of your own purpose,Whether you had not sometime in your life,Err’d in this point which now you censure him,And pull’d the law upon you." 
separator="," />
</ncml:netcdf>
```

**Comment by hyoklee** [comment]
Don't you see the problem? How many strings does NcML have with separator ','?

**Comment by ajelenak-thg** [comment]
That is not the point here. Separator can be specified to be some other character. The point that string array attributes are supported by both netCDF-C and netCDF-Java.

**Comment by hyoklee** [comment]
How? How about NcML importer?

**Comment by ajelenak-thg** [comment]
What NcML importer?

**Comment by hyoklee** [comment]
If you support array of strings, NcML importer should honor the separator and it will not give the same design. 

Also, how about this case?

ec2-user@ip-172-31-15-26 testfiles]$ ncdump -h vlen_string_attr.h5 
ncdump: vlen_string_attr.h5: NetCDF: HDF error

**Comment by hyoklee** [comment]
#81 will fix this.
