### ISSUE TITLE
REFERENCE_LIST attribute values in dimscale design should not be strings

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#8]
According to h5serv's [dim_scale.json](https://github.com/HDFGroup/h5serv/blob/5a5fc13c5a9fe04a42e1dfc3996b1fe3cd76bb31/testjson/dim_scale.json#L37) REFERENCE_LIST attribute values are not strings. In dimscale design in PD server these values are:

```
"value": [
    "[\"dataset/837dc7ef-bf64-44e4-8982-798d669cc822\", 0]"
]
```

Should be:

```
"value": [
    ["dataset/837dc7ef-bf64-44e4-8982-798d669cc822", 0]
]
```

**Comment by hyoklee** [comment]
I think I fixed the design on server. Can you validate it?

**Comment by ajelenak-thg** [comment]
Fixed.
