### ISSUE TITLE
Typo in dataset collection name for DIMENSION_LIST and REFERENCE_LIST attributes

### ISSUE THREAD

**Issue by ajelenak-thg** [HDFGroup/hpd#9]
The dataset collection name used when specifying dataset object references in DIMENSION_LIST and REFERENCE_LIST attributes should be ``datasets`` not ``dataset``. Example:

```
"value": [
    ["datasets/837dc7ef-bf64-44e4-8982-798d669cc822", 0]
]
```

**Comment by hyoklee** [comment]
I think I fixed the design on server. Can you validate it?

**Comment by ajelenak-thg** [comment]
Fixed.
